spring.application.name=spring-backend

# Cloudinary
cloudinary.cloud-name=dm5ynafvv
cloudinary.api-key=763337751889362
cloudinary.api-secret=Your_Api_Secret

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/spsdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=surajpratapsingh2022@gmail.com
spring.mail.password=Your_Password
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true

# JWT
jwt.secret=XJIlCfRlaxPRY2b3+bSGixdTZjiZbkwPBYMJTV5dJUrQKOHjJWFP0vlxpCa/eqX5s4TzDPs8vmA7RztQW2Q+WA==